import { Company } from "@/types/company";

export const mockCompanies: Company[] = [
  {
    id: "1",
    name: "TechCorp Solutions",
    industry: "Technology",
    location: "San Francisco",
    size: "500-1000",
    website: "https://techcorp.example.com",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "2",
    name: "FinanceHub Inc",
    industry: "Finance",
    location: "New York",
    size: "1000-5000",
    website: "https://financehub.example.com",
    createdAt: new Date("2024-02-10"),
    updatedAt: new Date("2024-02-10"),
  },
  {
    id: "3",
    name: "Healthcare Plus",
    industry: "Healthcare",
    location: "Boston",
    size: "100-500",
    website: "https://healthcareplus.example.com",
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
  },
  {
    id: "4",
    name: "EduTech Learning",
    industry: "Education",
    location: "Austin",
    size: "50-100",
    website: "https://edutech.example.com",
    createdAt: new Date("2024-03-05"),
    updatedAt: new Date("2024-03-05"),
  },
  {
    id: "5",
    name: "RetailMart Global",
    industry: "Retail",
    location: "Chicago",
    size: "5000+",
    website: "https://retailmart.example.com",
    createdAt: new Date("2024-01-08"),
    updatedAt: new Date("2024-01-08"),
  },
  {
    id: "6",
    name: "Manufacturing Pro",
    industry: "Manufacturing",
    location: "Detroit",
    size: "1000-5000",
    website: "https://manufacturingpro.example.com",
    createdAt: new Date("2024-02-15"),
    updatedAt: new Date("2024-02-15"),
  },
  {
    id: "7",
    name: "CloudServe Systems",
    industry: "Technology",
    location: "Seattle",
    size: "500-1000",
    website: "https://cloudserve.example.com",
    createdAt: new Date("2024-01-25"),
    updatedAt: new Date("2024-01-25"),
  },
  {
    id: "8",
    name: "GreenEnergy Co",
    industry: "Energy",
    location: "Denver",
    size: "100-500",
    website: "https://greenenergy.example.com",
    createdAt: new Date("2024-03-12"),
    updatedAt: new Date("2024-03-12"),
  },
  {
    id: "9",
    name: "MediaWorks Studio",
    industry: "Media",
    location: "Los Angeles",
    size: "50-100",
    website: "https://mediaworks.example.com",
    createdAt: new Date("2024-02-20"),
    updatedAt: new Date("2024-02-20"),
  },
  {
    id: "10",
    name: "AutoDrive Motors",
    industry: "Automotive",
    location: "Detroit",
    size: "1000-5000",
    website: "https://autodrive.example.com",
    createdAt: new Date("2024-01-30"),
    updatedAt: new Date("2024-01-30"),
  },
  {
    id: "11",
    name: "FoodChain Logistics",
    industry: "Logistics",
    location: "Miami",
    size: "500-1000",
    website: "https://foodchain.example.com",
    createdAt: new Date("2024-02-05"),
    updatedAt: new Date("2024-02-05"),
  },
  {
    id: "12",
    name: "TravelBook Agency",
    industry: "Travel",
    location: "Orlando",
    size: "50-100",
    website: "https://travelbook.example.com",
    createdAt: new Date("2024-03-08"),
    updatedAt: new Date("2024-03-08"),
  },
];

export const industries = [
  "Technology",
  "Finance",
  "Healthcare",
  "Education",
  "Retail",
  "Manufacturing",
  "Energy",
  "Media",
  "Automotive",
  "Logistics",
  "Travel",
];

export const locations = [
  "San Francisco",
  "New York",
  "Boston",
  "Austin",
  "Chicago",
  "Detroit",
  "Seattle",
  "Denver",
  "Los Angeles",
  "Miami",
  "Orlando",
];

export const companySizes = ["1-50", "50-100", "100-500", "500-1000", "1000-5000", "5000+"];
